Portfolio Section 1 and 2
GreetyCr/Portfolio_Mobile_FIrst pull request #1
Opened 2023-04-26 21:22 UTC by GreetyCr

All comments in commits, worked on section 1 and 2
Navbar with own logo
Import of Fontawesome
Import of GoogleFonts (Roboto, Lato and Poppins)
Design from figma
Add assets (Logo and background image)

2023-04-26 22:02 UTC, levy002 reviewed
## Hello @GreetyCr 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :x: :x: 

You have submitted a project, that doesn't have a professional Reame file. Kindly make sure to remove all comments instructions in your Readme file. It will help you to have a clean and professional repo. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-26 22:41 UTC, AdnanOlarmmi requested changes
Hi @GreetyCr,

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Nice overall layout.
- Nice one using flexbox where appropriate.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 22:41 UTC, AdnanOlarmmi commented on style.css
> +  font-family: 'Roboto', sans-serif;
- [ ] Kindly ensure that you follow suit with all the design guidelines to achieve an optimized pixel-perfect design like you'll be doing in your next job. Note that everything must much as possible, the font size, font weight, margin, padding, background image, color, line height, font family, and the like.

- Your design
<img width="167" alt="image" src="https://user-images.githubusercontent.com/41163571/234716798-34a62c42-bc90-4172-a619-2dd9ffd06f77.png">

- Figma design
<img width="217" alt="right" src="https://user-images.githubusercontent.com/41163571/227010023-9fcfb014-309c-4293-ba46-014f8e1c0000.png">

I took the extra mile for your sake to confirm if the font existed and was for free, guess what? 
[it is!!!!!!!](https://fonts.google.com/specimen/Crete+Round?query=crete).

- You can always get the properties on Figma by clicking on the item, and then check the right side pane for the information. 😀 
- the header is crete, the subheading is roboto while the paragraph text is poppins. 😉

2023-04-26 22:41 UTC, AdnanOlarmmi commented on index.html
> +      </div>
- [ ] Kindly ensure that the list of icons is an `a` tag wrapped in a `li` tag then all wrapped in a `ul` tag.

something like this 

```
<ul>
  <li><a>home</a></li>
  <li><a>house</a></li>
  <li><a>yard</a></li>
  <li><a>apartment</a></li>
</ul>
```

This is good for semantic and user experience reasons respectively and also enables one to connect with the icons using the `href` attribute.

2023-04-26 22:41 UTC, AdnanOlarmmi commented on style.css
> +  display: flex;
- [ ] It is noticed that `display: flex` property is repeated multiple times, Kindly let us stick to the DRY principle by not repeating a property more than it should 🙂. This can be done by having a class called `.flex-row` or `.flex-column` and assigning it wherever possible as a class name in your `html` markup code.
```
.flex-row {
  display: flex;
}

.flex-column {
  display: flex;
  flex-direction: column;
}
```
- And kindly attend to any repetitions in your code 🙂.

2023-04-26 22:41 UTC, AdnanOlarmmi commented on style.css
- [ ] Kindly note that your design, is overflowing a little bit 😉, you can prevent this by making the body width `100vw` or any other method you deem fit.


![769cb33d-e751-41b5-aa54-dada8d26a208](https://user-images.githubusercontent.com/41163571/234717414-f0d5f093-2eef-4299-a54a-812d1fb3dcc4.gif)

2023-04-26 22:41 UTC, AdnanOlarmmi commented on index.html
> +      </div>
- [ ] Kindly follow semantic HTML guidelines in your code 🙃.
You should have something like this instead of repetitive `div`s this enhances SEOs.
```
<body>
  <header>
    <nav>
    <nav>
  </header>
  
  <main>
    <section>
    </section>
    <article>
    </article>
  </main>
  
  <footer>
    <section>
    </section>
  </footer>
</body>
```

check this [link](https://web.dev/learn/html/semantic-html/) to read, know and learn more about semantic HTML. 💯 😀.

2023-04-26 22:43 UTC, GreetyCr commented
@AdnanOlarmmi Hello, I was checking the review but I cloudn't see a review message or comment on this repo, is there a way this is missing by mistake? best regards @GreetyCr

2023-04-27 00:37 UTC, Efiamotu-1 requested changes
Hi @GreetyCr , 

![](https://camo.githubusercontent.com/a06454929d29b512682cd8b375641b59076b9e5fe1a367808e685e5bcb818de3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e32466d5957466c5a6a45794d7a49314f4455784d5455775a44686b595459355932526c4e6a4d334e7a4e6c4f574530596a4a684d695a6c634431324d563970626e526c636d35686246396e61575a7a583264705a6b6c6b4a6d4e305057632f7a3370696f6b77663057504838314d4f68752f67697068792e676966)

Great work on making the changes requested by a previous reviewer 👏 Your Code is Awesome! 💪
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive PR title and description
- ✔️ Correct GitHub flow 
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 00:37 UTC, Efiamotu-1 commented on README.md
> +
- [ ] since the deployed link is not ready rather than use `google` you can notify users that it is coming soon and putting an empty link like this `[Coming soon :rocket: ]()` and this will be the output [Coming soon :rocket: ]() :+1:

2023-04-27 00:37 UTC, Efiamotu-1 commented on README.md
> +
- [ ] You are to use your correct github repo link here just so users or recruiters can easily copy the link to this project and clone to their devices, kindly please add this correctly :+1:

2023-04-27 00:37 UTC, Efiamotu-1 commented on README.md
> +
- [ ] Since you are the only contributor to this repo you shouldn't be having more than a single author kindly remove the first author and preferably add microverse in your acknowledgement section thanking them as the inspiration behind the project. :+1:

2023-04-27 00:37 UTC, Efiamotu-1 commented on README.md
> +
- [ ] please Kindly remove these texts as they only serve descriptive purposes which are to guide you on how to customise this section of your readme file, once customized to your taste as you have done you do not need them anymore and you can take it off :+1:

2023-04-27 00:37 UTC, Efiamotu-1 commented on README.md
> +
- [ ] please Kindly remove these texts as they only serve descriptive purposes which are to guide you on how to customise this section of your readme file, once customized to your taste as you have done you do not need them anymore and you can take it off :+1:

2023-04-27 00:37 UTC, Efiamotu-1 commented on style.css
> +}
- [ ] from the figma design below and your design there seems to be overflowing text into the background image

> figma design
![header-portfolio](https://user-images.githubusercontent.com/89055502/234729394-f35e2cd5-b3b2-457d-a08b-79f152cf66f4.png)

> your design
![student-1-header](https://user-images.githubusercontent.com/89055502/234729430-9d7975ff-c7b2-4a32-8e9a-6e98510f9c14.png)

- [ ] This is occuring because the width of the text runs from the left to the right taking up even some amount of space allotted for the background image, you can control this by specify a specific width in % for the text making it responsive on all screen sizes as this would prevent it from going all the way and overflowing into the background image.
- [ ] On line 99 and in a couple of other places in your css file i noticed you are making use of the `min-width` as specified from the figma image, you are not required to do this as by default your content would take up the width of whatever screen size it is adjusted to without you specifying it :+1:

2023-04-27 00:37 UTC, Efiamotu-1 commented on index.html
> +      </li>
- [ ] The last reviewer suggested you make use of the `ul, li and a` tags to display the social icon which i see you tried implementing but unfortunately you didnt do it correctly, if you look back at the example he showed you your are supposed to wrap all of it first with  a `ul` tag but from line 39 you are wrapping it entirely with an `li` tag instead, kindly make this change and then instead of using `ul` for each item you make use of `li`n tags :+1: 

``` 
  <ul class="about-me__social-media flex_row">
        <li class="about-me__logo--container">
          <a href=""><i class="fa-brands fa-github about-me__logo"></i></a>
        </li>
   </ul>
```
> The example above is how your first social icon should be written in your `index.html file`

2023-04-27 03:49 UTC, GreetyCr commented
@Efiamotu-1 just wanted to thank you for being so cool with the feedback and appreciate the way it was delivered! hope to see you again in the future! (And I hope all the changes were correct, kinda scared ngl) Im going to uploaded first thing in the morning for another review and hopefully it works as it is supposed to, thank you for your time!

2023-04-27 13:41 UTC, divinecharlotte approved these changes
# Hello @GreetyCr    😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 
### To Highlight 💯

- No linters errors ✔️
- Descriptive Readme✔️
- Good communication with the reviewers





## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 14:02 UTC, merged